[build]
command = "npm run build"
publish = ".next"

[functions]
node_bundler = "esbuild"
directory = ".netlify/functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
condition = "!req.headers.accept || req.headers.accept.includes(\"text/html\")"
